### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by kirus21** [SistemasTecTlaxiaco/actividad-3-sintesis-kirus21#2]
[Sintesis.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-kirus21/files/9464297/Sintesis.pdf)

**Comment by Rmz-Rigo** [comment]
La sintesís es individual.

**Comment by josealfredo79** [comment]
Realizar la síntesis de manera individual

**Comment by kirus21** [comment]
[Sintesis.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-kirus21/files/9473067/Sintesis.pdf)

**Comment by kirus21** [comment]
corregido

**Comment by kirus21** [comment]
solo no cambie la ´portada el contenido se realizo de manera individual

**Comment by Rmz-Rigo** [comment]
CALIFICACION:17/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
